### ISSUE TITLE
'Bad Request' Error

### ISSUE THREAD

**Issue by Matthew-Gaydachuk** [VDS13/telegram-inline-calendar#1]
Hi there! Got this error while entering /start command 

_Unhandled rejection Error: TELEGRAM: 400 Bad Request: BUTTON DATA_INVALID_

Could you please provide some info - is the cause of this issue and how it can be solved?
Thank you

**Comment by VDS13** [comment]
> Hi there! Got this error while entering /start command 
> 
> 
> 
> _Unhandled rejection Error: TELEGRAM: 400 Bad Request: BUTTON DATA_INVALID_
> 
> 
> 
> Could you please provide some info - is the cause of this issue and how it can be solved?
> 
> Thank you
> 
> 
> 
> 

Hello, could you show the part of the code where the error occurs?

**Comment by Matthew-Gaydachuk** [comment]
<img width="690" alt="Screenshot 2023-01-02 at 12 44 06" src="https://user-images.githubusercontent.com/34865612/210221083-a65467c6-783f-470e-84d2-007d2e255254.png">
 For now it's just a starting point

**Comment by VDS13** [comment]
> <img alt="Screenshot 2023-01-02 at 12 44 06" width="690" src="https://user-images.githubusercontent.com/34865612/210221083-a65467c6-783f-470e-84d2-007d2e255254.png">
> 
> For now it's just a starting point


Thank you for your feedback.
The problem was the overflow of `callback_data` at some points. Released update `1.1.2`. Please check if it works now.

**Comment by Matthew-Gaydachuk** [comment]
@VDS13 Works perfectly! Thank you for your prompt support.
