### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by wowbae** [VDS13/telegram-inline-calendar#11]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/6a0add6c-780b-4d6e-a386-1e52556a7985)

issue then importing module with version 2

**Comment by VDS13** [comment]
@wowbae, #7

**Comment by wowbae** [comment]
nope, i cant pick time because "calendar is not defined"

**Comment by wowbae** [comment]
the same problem like #7 yes, but i cant solve :(

**Comment by wowbae** [comment]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/e63db256-b8c5-47c6-b7f9-070ad1da2ff2)

**Comment by wowbae** [comment]
@VDS13 Дмитрий, кажется вы тоже понимаете русский :) сможете помочь? или направить где искать ответ 🙏🏼

**Comment by VDS13** [comment]
@wowbae, А можете показать кусок кода с созданием экземпляра класса календаря?

**Comment by wowbae** [comment]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/79a5e04d-f4fc-48f2-b99c-db76b38bec5b)
календарь создается, но выбрать ничего не дает

**Comment by VDS13** [comment]
@wowbae, а можно ещё кусок с ```"callback_query:data"```

**Comment by wowbae** [comment]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/ec4cbb9e-8a93-4acb-9cd0-5e12c1ee4073)

**Comment by wowbae** [comment]
в ответ на кнопки сейчас ничего не происходит

**Comment by wowbae** [comment]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/e80b1353-d5d6-4f48-8de4-bcc48f862888)
вот тут undefined почему-то дает при нажатии на день в календаре, хотя calendar в виде объекта получает нормально

**Comment by VDS13** [comment]
> ![image](https://user-images.githubusercontent.com/65613753/266526572-e80b1353-d5d6-4f48-8de4-bcc48f862888.png) вот тут undefined почему-то дает при нажатии на день в календаре, хотя calendar в виде объекта получает нормально

У вас ```calendar.chats.get(ctx.chat.id)``` в экземпляре класса из функции ```createEvent```, при этом вы создаёте ещё один экземпляр в функции ```keyboardListener```, два экземпляра между собой не связаны.
Как один из вариантов, можете в функции передавать помимо ```ctx``` ещё и экземпляр класса.

**Comment by wowbae** [comment]
спасибо большое, поправил! подскажите еще пожалуйста, после выбора времени его можно получить в переменную? не нашел метода в документации

**Comment by VDS13** [comment]
> спасибо большое, поправил! подскажите еще пожалуйста, после выбора времени его можно получить в переменную? не нашел метода в документации

```js
if (ctx.msg.message_id == calendar.chats.get(ctx.chat.id)) {
     var res = calendar.clickButtonCalendar(ctx); ///возвращает в формате "string" дату-время или "-1"
}
```

**Comment by wowbae** [comment]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/9e6bd4cd-54f0-4e9d-bcae-9944f380a17c)
-1 при нажатии на день, и дату при нажатии на время, где то ошибка?

**Comment by wowbae** [comment]
![image](https://github.com/VDS13/telegram-inline-calendar/assets/65613753/63eb254a-1c2c-4629-ac50-b67657cc0aa8)
здесь вывожу

**Comment by VDS13** [comment]
В ```date_format``` укажите в каком формате будет возвращаться результат ```calendar.clickButtonCalendar(ctx)```.
Судя по логу, у вас сейчас указан ```DD-MM-YYYY```.
Попробуйте, допустим, ```DD-MM-YYYY HH:mm```

**Comment by wowbae** [comment]
получилось, спасибо большое!
