### ISSUE TITLE
Is it possible to not display a specific date and time?

### ISSUE THREAD

**Issue by Ks-Andrey** [VDS13/telegram-inline-calendar#12]
Can you tell me if it is possible to make the calendar appear without a specific date and time? And is it possible to make start_date together with time?

**Comment by VDS13** [comment]
Hello, @Ks-Andrey)
I don’t quite understand the question, can you be more specific?

**Comment by Ks-Andrey** [comment]
I'm making a tg bot for doctor's appointments. I need to make the selected date disappear from the calendar, can this be implemented?

**Comment by VDS13** [comment]
Great idea)
Not implemented at the moment, but I will try to release an update tomorrow/the day after tomorrow with the possibility of excluding certain dates/times.

**Comment by Ks-Andrey** [comment]
Thank you very much. Please make it possible to put not only date but also time in start_date)

**Comment by VDS13** [comment]
Wouldn't the `time_range` parameter instead of `start_time` work for you?

**Comment by Ks-Andrey** [comment]
Nope(
I want to do it this way. You can't book for a time that has already passed.

**Comment by VDS13** [comment]
@Ks-Andrey, The finalization took a little longer, I will release an update tomorrow.

**Comment by VDS13** [comment]
@Ks-Andrey , the functionality is implemented, you can update to 1.7.0 or 2.1.0)))

**Comment by VDS13** [comment]
@Ks-Andrey, Can I close the issue?
