### ISSUE TITLE
Changing days order

### ISSUE THREAD

**Issue by Matthew-Gaydachuk** [VDS13/telegram-inline-calendar#2]
Hi again! Could you please help me - how could i change this piece of code so that the days order starts from Monday?

<img width="1355" alt="Screenshot 2023-01-11 at 17 33 01" src="https://user-images.githubusercontent.com/34865612/211848723-73363ec8-b795-4fab-bba3-9979d7488d9e.png">

**Comment by VDS13** [comment]
@Matthew-Gaydachuk, Hi,
Today or tomorrow I will release an update with this option.
