### ISSUE TITLE
Change message

### ISSUE THREAD

**Issue by AguChaves92** [VDS13/telegram-inline-calendar#4]
Is there a way to change the message to other than please select a date?

**Comment by VDS13** [comment]
> Is there a way to change the message to other than please select a date?

Hello, Can you show an example of the result?

**Comment by AguChaves92** [comment]
Sure here:
![image](https://user-images.githubusercontent.com/85836863/222505603-6e77b96f-18eb-4f53-8960-db9f2de6da17.png)

when useing the command calenadr the message that displayes is please select a date. Is it possible to change it?

**Comment by VDS13** [comment]
> 

```js
const TOKEN = process.env.TELEGRAM_TOKEN || 'YOUR_TELEGRAM_BOT_TOKEN';
const {Telegraf} = require('telegraf');
const NavCalendar = require('telegram-inline-calendar')
const bot = new Telegraf(TOKEN);
const calendar = new NavCalendar(bot, {
    date_format: 'DD-MM-YYYY',
    language: 'en',
    bot_api: 'telegraf'
});
bot.start((ctx) => calendar.startNavCalendar(ctx.message));
bot.on("callback_query", (ctx) => {
    if (ctx.callbackQuery.message.message_id == calendar.chats.get(ctx.callbackQuery.message.chat.id)) {
        res = calendar.clickButtonCalendar(ctx.callbackQuery);
        if (res !== -1) {
            bot.telegram.sendMessage(ctx.callbackQuery.message.chat.id, `Your custom message with date(${res})`);
        }
    }
});
bot.launch();
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
```

**Comment by VDS13** [comment]
The `clickButtonCalendar` method itself returns the date in the format you choose, and can be further processed as you wish.
Examples:
```js
bot.on("callback_query", (ctx) => {
    if (ctx.callbackQuery.message.message_id == calendar.chats.get(ctx.callbackQuery.message.chat.id)) {
        res = calendar.clickButtonCalendar(ctx.callbackQuery);
        if (res !== -1) {
            bot.telegram.sendMessage(ctx.callbackQuery.message.chat.id, `Your custom message with date(${res})`);
        }
    }
});
```
```js
bot.on("callback_query", (ctx) => {
    if (ctx.callbackQuery.message.message_id == calendar.chats.get(ctx.callbackQuery.message.chat.id)) {
        res = calendar.clickButtonCalendar(ctx.callbackQuery);
        if (res !== -1) {
            console.log(`Your custom message with date(${res})`);
        }
    }
});
```

**Comment by VDS13** [comment]
@AguChaves92, 
I was able to help you?

**Comment by AguChaves92** [comment]
I don't mean the answer after picking the date, but before. 
As  I've understood it, the command tha launches the bot is this one right?:
`bot.start((ctx) => calendar.startNavCalendar(ctx.message));`

the triggers a response with a message and the calendar from the bot. I want to change that message.

**Comment by VDS13** [comment]
> I don't mean the answer after picking the date, but before. As I've understood it, the command tha launches the bot is this one right?: `bot.start((ctx) => calendar.startNavCalendar(ctx.message));`
> 
> the triggers a response with a message and the calendar from the bot. I want to change that message.

I'm sorry, I misunderstood you.
Tomorrow I will release an update with this functionality.

**Comment by AguChaves92** [comment]
thank you very much

**Comment by VDS13** [comment]
@AguChaves92 Released an update, please check.

**Comment by AguChaves92** [comment]
I see the custom message now thank you

**Comment by VDS13** [comment]
@AguChaves92, Can the issue be closed?

**Comment by VDS13** [comment]
@AguChaves92  ?

**Comment by AguChaves92** [comment]
sry, yes
